=== bheckel/code/sas/acc_hierarchical.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated by XML Spy should update if plan to use-->
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="acc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="study" type="studyType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="barcode_ID_9" type="xs:string"/>
	<xs:element name="collection_date" type="xs:string"/>
	<xs:element name="collection_time">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="08:15:00"/>
				<xs:enumeration value="09:15:00"/>
				<xs:enumeration value="09:30:00"/>
				<xs:enumeration value="10:15:00"/>
				<xs:enumeration value="10:30:00"/>
				<xs:enumeration value="11:05:00"/>
				<xs:enumeration value="12:30:00"/>
				<xs:enumeration value="13:00:00"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="num_tubes">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="participantType">
		<xs:sequence>
			<xs:element ref="site_ID"/>
			<xs:element ref="participant_ID"/>
			<xs:element ref="participant_Init"/>
			<xs:element name="visit" type="visitType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="participant_ID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="participant_Init">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="CMB"/>
				<xs:enumeration value="DMS"/>
				<xs:enumeration value="GHB"/>
				<xs:enumeration value="MBT"/>
				<xs:enumeration value="NEC"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="site_ID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AC101"/>
				<xs:enumeration value="BD001"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="specimenType">
		<xs:sequence>
			<xs:element ref="barcode_ID_9"/>
			<xs:element ref="tube_type"/>
			<xs:element ref="specimen_type"/>
			<xs:element ref="num_tubes"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="specimen_type" type="xs:string"/>
	<xs:complexType name="studyType">
		<xs:sequence>
			<xs:element ref="study_ID"/>
			<xs:element name="participant" type="participantType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="study_ID" type="xs:string"/>
	<xs:element name="tube_type" type="xs:string"/>
	<xs:complexType name="visitType">
		<xs:sequence>
			<xs:element ref="collection_date"/>
			<xs:element ref="collection_time"/>
			<xs:element ref="visit_num"/>
			<xs:element name="specimen" type="specimenType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="visit_num">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0"/>
				<xs:enumeration value="6"/>
				<xs:enumeration value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== bheckel/code/sas/acc.xml
<acc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="acc_hierarchical.xsd">
	<study>
		<study_ID>AB101</study_ID>
		<participant>
			<site_ID>AC101</site_ID>
			<participant_ID>1</participant_ID>
			<participant_Init>MBT</participant_Init>
			<visit>
				<collection_date>2002-06-13</collection_date>
				<collection_time>12:30:00</collection_time>
				<visit_num>0</visit_num>
				<specimen>
					<barcode_ID_9>106001</barcode_ID_9>
					<tube_type>05 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
				<specimen>
					<barcode_ID_9>106001</barcode_ID_9>
					<tube_type>07 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-06-22</collection_date>
				<collection_time>10:15:00</collection_time>
				<visit_num>6</visit_num>
				<specimen>
					<barcode_ID_9>106155</barcode_ID_9>
					<tube_type>02 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>2</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-06-24</collection_date>
				<collection_time>10:15:00</collection_time>
				<visit_num>9</visit_num>
				<specimen>
					<barcode_ID_9>106951</barcode_ID_9>
					<tube_type>02.5 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
		</participant>
		<participant>
			<site_ID>AC101</site_ID>
			<participant_ID>2</participant_ID>
			<participant_Init>GHB</participant_Init>
			<visit>
				<collection_date>2002-06-25</collection_date>
				<collection_time>13:00:00</collection_time>
				<visit_num>0</visit_num>
				<specimen>
					<barcode_ID_9>106051</barcode_ID_9>
					<tube_type>05 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
				<specimen>
					<barcode_ID_9>106051</barcode_ID_9>
					<tube_type>07 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-06-28</collection_date>
				<collection_time>09:30:00</collection_time>
				<visit_num>6</visit_num>
				<specimen>
					<barcode_ID_9>106150</barcode_ID_9>
					<tube_type>02 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>2</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-07-01</collection_date>
				<collection_time>09:15:00</collection_time>
				<visit_num>9</visit_num>
				<specimen>
					<barcode_ID_9>106962</barcode_ID_9>
					<tube_type>02.5 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
		</participant>
		<participant>
			<site_ID>AC101</site_ID>
			<participant_ID>3</participant_ID>
			<participant_Init>NEC</participant_Init>
			<visit>
				<collection_date>2002-07-02</collection_date>
				<collection_time>09:15:00</collection_time>
				<visit_num>0</visit_num>
				<specimen>
					<barcode_ID_9>106023</barcode_ID_9>
					<tube_type>05 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
				<specimen>
					<barcode_ID_9>106023</barcode_ID_9>
					<tube_type>07 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-07-07</collection_date>
				<collection_time>10:30:00</collection_time>
				<visit_num>6</visit_num>
				<specimen>
					<barcode_ID_9>106160</barcode_ID_9>
					<tube_type>02 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>2</num_tubes>
				</specimen>
			</visit>
		</participant>
		<participant>
			<site_ID>BD001</site_ID>
			<participant_ID>1</participant_ID>
			<participant_Init>CMB</participant_Init>
			<visit>
				<collection_date>2002-07-01</collection_date>
				<collection_time>09:15:00</collection_time>
				<visit_num>0</visit_num>
				<specimen>
					<barcode_ID_9>106163</barcode_ID_9>
					<tube_type>02 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>2</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-07-14</collection_date>
				<collection_time>11:05:00</collection_time>
				<visit_num>9</visit_num>
				<specimen>
					<barcode_ID_9>106932</barcode_ID_9>
					<tube_type>02.5 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
		</participant>
		<participant>
			<site_ID>BD001</site_ID>
			<participant_ID>3</participant_ID>
			<participant_Init>DMS</participant_Init>
			<visit>
				<collection_date>2002-08-15</collection_date>
				<collection_time>09:15:00</collection_time>
				<visit_num>0</visit_num>
				<specimen>
					<barcode_ID_9>106016</barcode_ID_9>
					<tube_type>05 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-08-21</collection_date>
				<collection_time>09:30:00</collection_time>
				<visit_num>6</visit_num>
				<specimen>
					<barcode_ID_9>106173</barcode_ID_9>
					<tube_type>02 ml EDTA</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>2</num_tubes>
				</specimen>
			</visit>
			<visit>
				<collection_date>2002-07-24</collection_date>
				<collection_time>08:15:00</collection_time>
				<visit_num>9</visit_num>
				<specimen>
					<barcode_ID_9>106917</barcode_ID_9>
					<tube_type>02.5 ml SST</tube_type>
					<specimen_type>whole blood</specimen_type>
					<num_tubes>1</num_tubes>
				</specimen>
			</visit>
		</participant>
	</study>
</acc>
